spring:
  application:
    name: Cartao API
  datasource:
    url: jdbc:h2:mem:cliente
    username: melyssa
    password: admin
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true
      path: /h2-console